Use correct info parameter and check for location
homotechsual/NinjaOne pull request #20
Opened 2023-04-04 08:04 UTC by aretokas

Not sure if this is how you would have done the location exists check, but it lines up with where it looked like the code was headed.

2023-04-04 22:14 UTC, homotechsual requested changes

2023-04-04 22:14 UTC, homotechsual commented on Public/Update/Update-NinjaOneLocation.ps1
> +        $LocationExists = $((Get-NinjaOneLocations -OrganisationId $organisationId) | ?{$_.id -eq $locationId}).Count -gt 0
```suggestion
        $LocationExists = $(Get-NinjaOneLocations -OrganisationId $organisationId | Where-Object { $_.id -eq $locationId }).Count) -gt 0
```

2023-04-04 22:15 UTC, homotechsual commented on Public/Update/Update-NinjaOneLocation.ps1
> +        $LocationExists = $((Get-NinjaOneLocations -OrganisationId $organisationId) | ?{$_.id -eq $locationId}).Count -gt 0
Yeah exactly what I'd have done except - no aliases (just for coding standards really)

2023-04-05 03:01 UTC, aretokas commented on Public/Update/Update-NinjaOneLocation.ps1
> +        $LocationExists = $((Get-NinjaOneLocations -OrganisationId $organisationId) | ?{$_.id -eq $locationId}).Count -gt 0
That's me being lazy 😅 Happy to avoid aliases in future. Commited.

2023-04-05 10:07 UTC, merged